const colors = ['#0a72ef', '#00ddd7', '#7c28c8', '#eb367f', '#fc6d26', '#fac92b'];

const titles = [
	'Grocery Shopping List',
	'Ideas for Vacation',
	'Meeting with Clients',
	'Workout Routine',
	'Book Recommendations',
	'Recipes to Try',
	'Project Ideas',
	'Daily To-Do List',
	'Budget Planning',
	'Inspirational Quotes',
	'Gift Ideas for Birthday',
	'Movie Recommendations',
	'Goals for the Month',
	'Party Planning',
	'Home Improvement Ideas',
	'Journal Entry',
	'Places to Visit',
	'Important Dates',
	'Fitness Tracker',
	'Brainstorming Session',
	'Weekly Meal Plan',
	'Shopping Wishlist',
	'Travel Itinerary',
	'Creative Writing Prompts',
	'DIY Projects',
	'Reflections on Life',
	'Study Schedule',
	'Bucket List',
	'Favorite Quotes',
	'Business Ideas',
	'Daily Affirmations',
	'Art Sketches',
	'Concert Wish List',
	'Mindfulness Exercises',
	'Podcast Recommendations',
	'Holiday Gift List',
	'Inspirational Stories',
	'Health and Wellness Tips',
	'Motivational Thoughts',
	'Financial Goals',
	'Self-Care Ideas',
	'New Recipes to Explore',
	'Quotes to Remember',
	'Hobby Ideas',
	'Language Learning Tips',
	'Home Organization Ideas',
	'Book Summaries',
	'Gardening Tips',
	'Inspirational Song Lyrics',
	'Personal Growth Strategies',
];

const contents = [
	'The sun was shining on the peaceful meadow, and the birds were singing their melodious tunes.',
	'She walked along the sandy beach, feeling the cool breeze brush against her face.',
	'In the bustling city, people hurriedly went about their daily routines, lost in their own thoughts.',
	'The old oak tree stood tall in the middle of the forest, its branches reaching towards the sky.',
	'As the train pulled into the station, passengers eagerly awaited their arrival at their destination.',
	'The aroma of freshly brewed coffee filled the air, creating a warm and inviting atmosphere.',
	'He gazed up at the stars, marveling at the vastness of the universe and his place within it.',
	'The children played joyfully in the park, their laughter echoing through the afternoon air.',
	'With each brushstroke, the artist brought the canvas to life, creating a masterpiece.',
	'The sound of rain tapping against the window created a soothing and calming ambiance.',
	`Jelly sweet roll jelly beans biscuit pie macaroon chocolate donut. Carrot cake caramels pie sweet apple pie tiramisu carrot cake. Marzipan marshmallow croissant tootsie roll lollipop. Cupcake lemon drops bear claw gummies. Jelly bear claw gummi bears lollipop cotton candy gummi bears chocolate bar cake cookie. Cupcake muffin danish muffin cookie gummies. Jelly beans tiramisu pudding. Toffee soufflé chocolate cake pastry brownie. Oat cake halvah sweet roll cotton candy croissant lollipop. Macaroon tiramisu chocolate bar candy candy carrot cake jelly sweet. Gummies croissant macaroon dessert. Chocolate cake dragée pie.`,
	`Next level tbh everyday carry, blog copper mug forage kitsch roof party pickled hammock kale chips tofu. Etsy shoreditch 8-bit microdosing, XOXO viral butcher banh mi humblebrag listicle woke bicycle rights brunch before they sold out ramps. Twee shabby chic taiyaki flannel, enamel pin venmo vape four loko. Hexagon kale chips typewriter kitsch 8-bit organic plaid small batch keffiyeh ethical banh mi narwhal echo park cronut.`,
	`Zombie ipsum reversus ab viral inferno, nam rick grimes malum cerebro. De carne lumbering animata corpora quaeritis. Summus brains sit​​, morbo vel maleficia? De apocalypsi gorger omero undead survivor dictum mauris. Hi mindless mortuis soulless creaturas, imo evil stalking monstra adventus resi dentevil vultus comedat cerebella viventium. Qui animated corpse, cricket bat max brucks terribilem incessu zomby. The voodoo sacerdos flesh eater, suscitat mortuos comedere carnem virus. Zonbi tattered for solum oculi eorum defunctis go lum cerebro. Nescio brains an Undead zombies. Sicut malus putrid voodoo horror. Nigh tofth eliv ingdead.`,
	`Cat gets stuck in tree firefighters try to get cat down firefighters get stuck in tree cat eats firefighters' slippers kitty power ignore the squirrels, you'll never catch them anyway for what a cat-ass-trophy! or purr as loud as possible, be the most annoying cat that you can, and, knock everything off the table. Pretend you want to go out but then don't bite off human's toes, yet disappear for four days and return home with an expensive injury; bite the vet so catch eat throw up catch eat throw up bad birds. `,
	`This opera's as lousy as it is brilliant! Your lyrics lack subtlety. You can't just have your characters announce how they feel. That makes me feel angry! Anyhoo, your net-suits will allow you to experience Fry's worm infested bowels as if you were actually wriggling through them. I just told you! You've killed me! Fry! Quit doing the right thing, you jerk! Michelle, I don't regret this, but I both rue and lament it. Morbo can't understand his teleprompter because he forgot how you say that letter that's shaped like a man wearing a hat.`,
	`Airedale hard cheese mozzarella. Pecorino melted cheese port-salut emmental babybel cheese and wine melted cheese manchego. Everyone loves blue castello everyone loves fromage cheese slices airedale cheddar cream cheese. Bavarian bergkase who moved my cheese halloumi port-salut gouda jarlsberg ricotta rubber cheese. Stinking bishop smelly cheese brie.`,
	`Salvia glossier subway tile, leggings mustache YOLO semiotics chia. Pitchfork tbh af blog church-key meggings vaporware PBR&B master cleanse post-ironic man bun pabst mustache letterpress synth. Snackwave raw denim godard, 3 wolf moon shaman offal kitsch unicorn live-edge selvage schlitz fashion axe vaporware drinking vinegar prism. Shabby chic tacos artisan, chambray chicharrones cardigan leggings typewriter af pop-up williamsburg meditation PBR&B viral. You probably haven't heard of them DIY jean shorts subway tile fashion axe bushwick kitsch tumeric cloud bread vaporware freegan franzen pork belly chicharrones banh mi.`,
	`Man braid celiac synth freegan readymade, pitchfork fam salvia waistcoat lomo bitters gentrify four loko. Pitchfork semiotics post-ironic vegan. Tofu meditation microdosing hashtag semiotics venmo. Flexitarian vape tilde taiyaki. Prism poutine farm-to-table, messenger bag vegan taxidermy tattooed sartorial squid jean shorts fixie selvage trust fund vape.`,
	`Rutters Plate Fleet boom chandler Brethren of the Coast handsomely lookout marooned brigantine knave. Buccaneer gangway jack rum loot spyglass line Jack Tar fore gaff. Gaff topmast scuttle ballast swab draught measured fer yer chains dance the hempen jig Chain Shot yardarm.`,
	"The majestic waterfall cascaded down the rugged cliffside, creating a breathtaking display of nature's power and beauty. The rushing water sparkled under the sunlight, casting a mesmerizing spray that danced in the air. Standing there, in awe of the magnificent sight, one couldn't help but feel a sense of tranquility and wonder. It was a moment frozen in time, a reminder of the incredible wonders that exist in our world.",
	'The old bookstore was filled with shelves upon shelves of books, each one holding a different story waiting to be discovered. The smell of aged paper and ink lingered in the air, evoking a sense of nostalgia. As I walked through the narrow aisles, I could feel the weight of knowledge and imagination surrounding me. It was a sanctuary for the curious minds, a place where one could get lost in the pages and find themselves in a world beyond their own.',
	"The sun slowly set behind the horizon, painting the sky with vibrant hues of orange and pink. The tranquil waves gently caressed the shoreline, creating a soothing symphony of nature. Seagulls soared gracefully above, their cries echoing in the distance. It was a moment of serenity, a pause in the hustle and bustle of everyday life. As I watched the colors fade and the stars emerge, I couldn't help but feel a sense of gratitude for the simple beauty that surrounded me.",
	'The bustling market was filled with vibrant colors and enticing aromas. Vendors shouted out their offers, tempting passersby with their fresh produce and delicious treats. The air was filled with the sounds of laughter, bargaining, and the occasional clinking of coins. People hurriedly went about their business, eager to find the perfect ingredients for their meals. It was a lively atmosphere, a melting pot of cultures and flavors, where one could immerse themselves in the rich tapestry of the local community.',
	'The ancient ruins stood as a testament to the passage of time. Weathered by centuries of history, they carried the stories of civilizations long gone. As I walked among the crumbling walls and fallen pillars, I could almost hear the whispers of the past. It was a humbling experience, a glimpse into the grandeur and fragility of human existence. In that moment, I realized that even the mightiest empires eventually fade away, but their legacy remains etched in the stones.',
	'The sound of laughter filled the air as families gathered for a picnic in the park. Children ran freely, their carefree spirits lifting the hearts of those around them. The scent of freshly cut grass mingled with the sweet aroma of blooming flowers. Friends shared stories and laughter, creating memories that would last a lifetime. It was a day of simple joys and cherished connections, a reminder of the importance of love and togetherness in our lives.',
	'The winding mountain trail led me to a breathtaking vista. From the summit, I could see the world stretching out before me, vast and full of possibilities. The cool breeze brushed against my skin, rejuvenating my spirit. In that moment, I felt a sense of clarity and freedom, as if I had left all my worries behind. It was a reminder that sometimes, the journey itself is just as important as the destination.',
];

export { colors, titles, contents };
